kind: PersistentVolume
apiVersion: v1
metadata:
  name: test-pv-volume
  labels:
    type: local
spec:
  storageClassName: general
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/pod_storage"
